# Generated by Django 3.0.6 on 2020-05-10 07:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student_home', '0003_auto_20200510_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q_answer',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='student_home.Answer'),
            preserve_default=False,
        ),
    ]
