# Generated by Django 3.0.6 on 2020-05-10 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_home', '0004_question_q_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='q_answer',
        ),
    ]
