# Generated by Django 3.0.6 on 2020-05-10 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_home', '0006_auto_20200510_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('can_update', 'Can update questions')]},
        ),
    ]
