# Generated by Django 3.0.6 on 2020-05-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subject',
            new_name='usn',
        ),
    ]
