# Generated by Django 3.0.6 on 2020-05-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200509_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='usn',
        ),
    ]
